import { ColorValue } from 'react-native';
import { Colors } from './Colors';
export type Theme = {
  primary: ColorValue;
  onPrimary: ColorValue;
  primaryContainer: ColorValue;
  onPrimaryContainer: ColorValue;
  secondary: ColorValue;
  onSecondary: ColorValue;
  secondaryContainer: ColorValue;
  onSecondaryContainer: ColorValue;
  tertiary: ColorValue;
  onTertiary: ColorValue;
  tertiaryContainer: ColorValue;
  onTertiaryContainer: ColorValue;
  error: ColorValue;
  onError: ColorValue;
  errorContainer: ColorValue;
  onErrorContainer: ColorValue;
  background: ColorValue;
  onBackground: ColorValue;
  surface: ColorValue;
  onSurface: ColorValue;
  surfaceVariant: ColorValue;
  onSurfaceVariant: ColorValue;
  outline: ColorValue;
  outlineVariant: ColorValue;
  scrim: ColorValue;
  inverseSurface: ColorValue;
  inverseOnSurface: ColorValue;
  inversePrimary: ColorValue;
  surfaceDim: ColorValue;
  surfaceBright: ColorValue;
  surfaceContainerLowest: ColorValue;
  surfaceContainerLow: ColorValue;
  surfaceContainer: ColorValue;
  surfaceContainerHigh: ColorValue;
  surfaceContainerHighest: ColorValue;
  success: ColorValue;
};

export const LightMode: Theme = {
  primary: Colors.primaryLight,
  onPrimary: Colors.onPrimaryLight,
  primaryContainer: Colors.primaryContainerLight,
  onPrimaryContainer: Colors.onPrimaryContainerLight,
  secondary: Colors.secondaryLight,
  onSecondary: Colors.onSecondaryLight,
  secondaryContainer: Colors.secondaryContainerLight,
  onSecondaryContainer: Colors.onSecondaryContainerLight,
  tertiary: Colors.tertiaryLight,
  onTertiary: Colors.onTertiaryLight,
  tertiaryContainer: Colors.tertiaryContainerLight,
  onTertiaryContainer: Colors.onTertiaryContainerLight,
  error: Colors.errorLight,
  onError: Colors.onErrorLight,
  errorContainer: Colors.errorContainerLight,
  onErrorContainer: Colors.onErrorContainerLight,
  background: Colors.backgroundLight,
  onBackground: Colors.onBackgroundLight,
  surface: Colors.surfaceLight,
  onSurface: Colors.onSurfaceLight,
  surfaceVariant: Colors.surfaceVariantLight,
  onSurfaceVariant: Colors.onSurfaceVariantLight,
  outline: Colors.outlineLight,
  outlineVariant: Colors.outlineVariantLight,
  scrim: Colors.scrimLight,
  inverseSurface: Colors.inverseSurfaceLight,
  inverseOnSurface: Colors.inverseOnSurfaceLight,
  inversePrimary: Colors.inversePrimaryLight,
  surfaceDim: Colors.surfaceDimLight,
  surfaceBright: Colors.surfaceBrightLight,
  surfaceContainerLowest: Colors.surfaceContainerLowestLight,
  surfaceContainerLow: Colors.surfaceContainerLowLight,
  surfaceContainer: Colors.surfaceContainerLight,
  surfaceContainerHigh: Colors.surfaceContainerHighLight,
  surfaceContainerHighest: Colors.surfaceContainerHighestLight,
  success: Colors.success,
};

export const DarkMode: Theme = {
  primary: Colors.primaryDark,
  onPrimary: Colors.onPrimaryDark,
  primaryContainer: Colors.primaryContainerDark,
  onPrimaryContainer: Colors.onPrimaryContainerDark,
  secondary: Colors.secondaryDark,
  onSecondary: Colors.onSecondaryDark,
  secondaryContainer: Colors.secondaryContainerDark,
  onSecondaryContainer: Colors.onSecondaryContainerDark,
  tertiary: Colors.tertiaryDark,
  onTertiary: Colors.onTertiaryDark,
  tertiaryContainer: Colors.tertiaryContainerDark,
  onTertiaryContainer: Colors.onTertiaryContainerDark,
  error: Colors.errorDark,
  onError: Colors.onErrorDark,
  errorContainer: Colors.errorContainerDark,
  onErrorContainer: Colors.onErrorContainerDark,
  background: Colors.backgroundDark,
  onBackground: Colors.onBackgroundDark,
  surface: Colors.surfaceDark,
  onSurface: Colors.onSurfaceDark,
  surfaceVariant: Colors.surfaceVariantDark,
  onSurfaceVariant: Colors.onSurfaceVariantDark,
  outline: Colors.outlineDark,
  outlineVariant: Colors.outlineVariantDark,
  scrim: Colors.scrimDark,
  inverseSurface: Colors.inverseSurfaceDark,
  inverseOnSurface: Colors.inverseOnSurfaceDark,
  inversePrimary: Colors.inversePrimaryDark,
  surfaceDim: Colors.surfaceDimDark,
  surfaceBright: Colors.surfaceBrightDark,
  surfaceContainerLowest: Colors.surfaceContainerLowestDark,
  surfaceContainerLow: Colors.surfaceContainerLowDark,
  surfaceContainer: Colors.surfaceContainerDark,
  surfaceContainerHigh: Colors.surfaceContainerHighDark,
  surfaceContainerHighest: Colors.surfaceContainerHighestDark,
  success: Colors.success,
};
